/**
 * The project structure is as follows: 
 * src
 *    -> components folder
 *          -> counter.js
 *          -> navbar.js
 *          -> toggleMessage.js
 *    -> pages folder
 *          -> about.js
 *          -> contact.js
 *                -> ContactForm component
 *          -> index.js
 *                *** The components inside the component folder belong to Home page (index.js).
 *    -> styles folder
 * 
 * This application includes 3 pages: Home (index.js), About (about.js), contact (contact.js).
 * 
 */
import Head from 'next/head';
import styles from "@/styles/Home.module.css";
import Navbar from '../components/navbar';
import Counter from '../components/counter';
import ToggleMessage from '../components/toggleMessage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.container}>
        <h1 className={styles.title}>Welcome to My Next.js App!</h1>
        <Navbar />
          <div className={styles.componentWrapper}>
            <h2 className={styles.componentTitle}>Let's count: </h2>
            <Counter />
          </div>
          <div className={styles.componentWrapper}>
            <h2 className={styles.componentTitle}>Today's Message: </h2>
            <ToggleMessage />
          </div>
      </div>
    </>
  );
}
